### ISSUE TITLE
Modifications and updates

### ISSUE THREAD

**Issue by ghost** [exsaol24/pokedex#1]
Will you continue to modificate and update the Pokedex?

**Comment by exsaol24** [comment]
Absolutely! As a development team, we are always looking for ways to improve and update our projects, including the Pokédex. We recognize that information and data about Pokémon is constantly evolving, whether it be with new games, movies, or series, as well as new Pokémon being added to the franchise. Therefore, we are committed to staying up to date and providing the most accurate and up-to-date information possible to Pokémon lovers. We will continue to make regular updates to reflect changes to the franchise and ensure a rich user experience.

**Comment by exsaol24** [comment]
close
